# Generated by Django 3.2.6 on 2021-09-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutbelarus', '0002_usersendmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersendmessage',
            options={'ordering': ['-time_sending'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterField(
            model_name='usersendmessage',
            name='message',
            field=models.CharField(blank=True, max_length=250, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='usersendmessage',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='usersendmessage',
            name='time_sending',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время'),
        ),
    ]
