# Generated by Django 3.2.6 on 2021-09-20 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutbelarus', '0004_alter_usersendmessage_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersendmessage',
            options={'ordering': ['id'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
