# Generated by Django 3.2.6 on 2021-09-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutbelarus', '0005_alter_usersendmessage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersendmessage',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='usersendmessage',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
    ]
