# Generated by Django 3.2.6 on 2021-09-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutbelarus', '0007_alter_usersendmessage_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersendmessage',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='E-mail'),
        ),
    ]
